
import random

def GetFlavorText(PlayerName):
    FlavorList = [
    "PLAYER forgot how to live.",
    "PLAYER took a dirt nap.",
    "PLAYER died, it was a skill issue.",
    "PLAYER was owned. Hard.",
    "PLAYER went full noob.",
    "PLAYER became XP for others.",
    "PLAYER tried their best. Lol.",
    "PLAYER got rekt, GG.",
    "PLAYER died of style points.",
    "PLAYER pressed F too late.",
    "PLAYER got clapped.",
    "PLAYER mistimed that jump.",
    "PLAYER lagged to death.",
    "PLAYER got surprise deleted.",
    "PLAYER failed the tutorial.",
    "PLAYER got memed to death.",
    "PLAYER was a free kill.",
    "PLAYER tripped over victory.",
    "PLAYER ran out of luck.",
    "PLAYER underestimated gravity.",
    "PLAYER embraced the respawn.",
    "PLAYER blinked and died.",
    "PLAYER died of embarrassment.",
    "PLAYER got outplayed. Badly.",
    "PLAYER walked into that one.",
    "PLAYER forgot to dodge.",
    "PLAYER stood still. Oof.",
    "PLAYER forgot their armor.",
    "PLAYER panic-rolled to death.",
    "PLAYER touched the red zone.",
    "PLAYER was too curious.",
    "PLAYER went out with a whimper.",
    "PLAYER joined the ghost club.",
    "PLAYER rage-alt-F4’d IRL.",
    "PLAYER found the kill zone.",
    "PLAYER mistook friend for foe.",
    "PLAYER died doing a TikTok.",
    "PLAYER got yeeted.",
    "PLAYER pressed the wrong key.",
    "PLAYER caught a stray.",
    "PLAYER lost the plot.",
    "PLAYER was deleted by karma.",
    "PLAYER forgot how guns work.",
    "PLAYER got combo’d to bits.",
    "PLAYER became loot.",
    "PLAYER was fragged into history.",
    "PLAYER got sniped by fate.",
    "PLAYER died like a true gamer.",
    "PLAYER failed their last quest.",
    "PLAYER was out of heals.",
    "Took an L, and it was fatal for PLAYER.",
    "Gravity had beef with PLAYER.",
    "One moment alive, then poof — PLAYER.",
    "The floor betrayed PLAYER.",
    "Respawn incoming for PLAYER.",
    "That explosion really liked PLAYER.",
    "Bad timing ended PLAYER.",
    "Death speedran PLAYER.",
    "It was a trap... PLAYER fell for it.",
    "That boss just deleted PLAYER.",
    "Lag claimed PLAYER again.",
    "That frag had PLAYER’s name on it.",
    "An NPC outplayed PLAYER.",
    "The final flash seen by PLAYER.",
    "A bad idea took PLAYER out.",
    "That wall won against PLAYER.",
    "Surprise mechanics ended PLAYER.",
    "A door said no to PLAYER.",
    "PLAYER became background lore.",
    "That rocket found PLAYER.",
    "Loot was a trap. Sorry, PLAYER.",
    "A bug ate PLAYER whole.",
    "A bush sniped PLAYER.",
    "PLAYER got distracted... permanently.",
    "The stairs fought back at PLAYER.",
    "The respawn screen comforted PLAYER.",
    "It was a bold move by PLAYER.",
    "The scoreboard laughed at PLAYER.",
    "Physics took revenge on PLAYER.",
    "One misstep later, no more PLAYER.",
    "A crit ended PLAYER’s dreams.",
    "PLAYER misread the situation.",
    "A chicken outplayed PLAYER.",
    "The AFK gods punished PLAYER.",
    "That corner had it out for PLAYER.",
    "A no-scope ended PLAYER’s run.",
    "PLAYER went exploring... and died.",
    "Style over survival — classic PLAYER.",
    "A barrel ruined PLAYER’s day.",
    "PLAYER joined the “Oops” club.",
    "PLAYER died waiting for an item.",
    "PLAYER needed a sword... and died.",
    "Archipelago rerouted PLAYER to death.",
    "PLAYER got nothing... except dead.",
    "PLAYER trusted a hint. Mistake.",
    "A fetch quest killed PLAYER.",
    "PLAYER died before the item arrived.",
    "A trap chest claimed PLAYER.",
    "PLAYER walked into logic’s trap.",
    "PLAYER perished chasing progression.",
    ]
    return (random.choice(FlavorList)).replace("PLAYER", PlayerName)