services:
  bridgeipelago:
    build: .
    volumes:
      - ./bridgeipelago/logs:/bridgeipelago/logs
      - ./bridgeipelago/registrationdata:/bridgeipelago/registrationdata
      - ./bridgeipelago/itemqueue:/bridgeipelago/itemqueue
      - ./bridgeipelago/archdata:/bridgeipelago/archdata
      - ./bridgeipelago/config.json:/bridgeipelago/config.json
    working_dir: /bridgeipelago
    restart: unless-stopped
