services:
  bridgeipelago:
    build: .
    volumes:
      - ./bridgeipelago/logs:/bridgeipelago/logs
      - ./bridgeipelago/RegistrationData:/bridgeipelago/RegistrationData
      - ./bridgeipelago/ItemQueue:/bridgeipelago/ItemQueue
      - ./bridgeipelago/ArchData:/bridgeipelago/ArchData
      - ./config.json:/bridgeipelago
    working_dir: /bridgeipelago
    restart: unless-stopped
